// <auto-generated />
namespace WebPageEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class webSiteInit92 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(webSiteInit92));
        
        string IMigrationMetadata.Id
        {
            get { return "201701231520438_webSiteInit92"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
