// <auto-generated />
namespace WebPageEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class webSiteInit91 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(webSiteInit91));
        
        string IMigrationMetadata.Id
        {
            get { return "201701231105152_webSiteInit91"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
